# Don't print a new line at the start of the prompt
add_newline = true
format = '$time$username$hostname$directory\\n$character'

# Replace the "â¯" symbol in the prompt with "âœ"
[character]
success_symbol = "[âœ ](bold green)"
error_symbol = "[âœ ](bold red)"

# Disable the package module, hiding it from the prompt completely
#[package]
#disabled = true

#[battery]
#full_symbol = "ğŸ”‹"
#charging_symbol = "âš¡ï¸"
#discharging_symbol = "ğŸ’€"

[time]
disabled = true
format = '[$time](#ff9900) '
time_format = "%T"
#utc_time_offset = ""
#time_range = "10:00:00-14:00:00"

[username]
style_user = "#d00b0b bold"
style_root = "black bold"
format = "[$user@](bold $style)"
disabled = true
show_always = true
#ssh_only = true

[hostname]
ssh_only = false
format =  "[$hostname ](bold #d00b0b)"
#trim_at = ".companyname.com"
disabled = false

[directory]
truncation_length = 30
style = ""
